### ISSUE TITLE
Support factom-walletd RPC authentication

### ISSUE THREAD

**Issue by WhoSoup** [Factom-Asset-Tokens/factom#15]
factom-walletd supports basic http authorization protection for connection (though they call it RPC authentication), however there's no way to set this in the client.

**Comment by AdamSLevy** [comment]
This has long been supported in the jsonrpc2.Client. Use jsonrpc2.Client.User, jsonrpc2.Client.Password, and set jsonrpc2.BasicAuth = true before calling jsonrpc2.Client.Request. Additional headers can also be added using jsonrpc2.Client.Headers.

The factom.Client has two jsonrpc2.Clients. One for factomd and one for factom-walletd. So you can set separate basic http auth settings for each endpoint.
