### ISSUE TITLE
API Endpoint doesn't check for trailing slash

### ISSUE THREAD

**Issue by WhoSoup** [Factom-Asset-Tokens/factom#9]
Client.FactomdRequest/WalletdRequest just tacks on "/v2" without checking to see if the provided url already has a trailing slash. 

This works:
```go
	cli := &factom.Client{FactomdServer: "https://api.factomd.net"}
	h := new(factom.Heights)
	fmt.Println(h.Get(cli))
```

This doesn't work:
```go
	cli := &factom.Client{FactomdServer: "https://api.factomd.net/"}
	h := new(factom.Heights)
	fmt.Println(h.Get(cli))
```

**Comment by AdamSLevy** [comment]
The proper way to handle this would be to use `net/url` and call `url.Parse()` and check for the `URL{}.Path` string. I'd accept a PR for this but I'll get around to it eventually.

**Comment by AdamSLevy** [comment]
It is now entirely up to client to have the request URL correct. The trailing `/v2` is no longer appended and clients must add this path to their URLs if needed for the servers they are connecting to.
